spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: marketplace
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
    generate-ddl: true
